import {
  Biokefir,
  Butter,
  CondensedMilk,
  Curd,
  Kefir,
  Milk,
  ProcessedChocolateCheese,
  SourCream,
  Strawberry,
  Smetana,
  ProcessedCheese,
  BlueKefir,
  CurdChocolate,
  CurdKiwi,
  CurdStrawberry,
  MiniCondensedMilk,
  KefirWoilet,
  SlideOne,
  SlideTwo,
  SlideThree,
  SlideFour,
  SlideFive,
  ItemTwo,
  ItemThree,
  ItemFour,
  ItemFive,
} from "../assets/index.js"

export const cardItems = [
  {
    id: 1,
    title: "Молоко",
    width: "250px",
    height: "400px",
    colorCard: "#B49FC3",
    gradient: "61.76% 61.76% at 50% 50%, #A692BE 0%, #7B669F 100%",
    description:
      "С проверенными продуктами готовить одно удовольствие. Они не подведут, они гарантируют результат. Именно поэтому они вдохновляют на новые кулинарные свершения. Молочные продукты под торговой маркой «ЭКОМИЛК» – те самые продукты, которые уже много лет занимают свое почетное место в холодильниках и ведут хозяек на новые кулинарные подвиги.",
    image: Milk,
  },
  {
    id: 2,
    title: "БИО Кефиры",
    width: "270px",
    height: "410.9px",
    colorCard: "#B5CB07",
    gradient: "177.19% 103.61% at 78.44% 53.24%, #B6E522 0%, #DED37B 100%",

    description:
      "С проверенными продуктами готовить одно удовольствие. Они не подведут, они гарантируют результат. Именно поэтому они вдохновляют на новые кулинарные свершения. Молочные продукты под торговой маркой «ЭКОМИЛК» – те самые продукты, которые уже много лет занимают свое почетное место в холодильниках и ведут хозяек на новые кулинарные подвиги.",
    image: Biokefir,
  },
  {
    id: 3,
    title: "Масло",
    width: "260px",
    height: "350.9px",
    colorCard: "#D2AF4A",
    gradient: "177.19% 103.61% at 78.44% 53.24%, #EED489 0%, #C29C35 92.19%",

    description:
      "С проверенными продуктами готовить одно удовольствие. Они не подведут, они гарантируют результат. Именно поэтому они вдохновляют на новые кулинарные свершения. Молочные продукты под торговой маркой «ЭКОМИЛК» – те самые продукты, которые уже много лет занимают свое почетное место в холодильниках и ведут хозяек на новые кулинарные подвиги.",
    image: Butter,
  },
  {
    id: 4,
    title: "Каймак",
    width: "290px",
    height: "220px",
    colorCard: "#A5BADD",
    gradient: "177.19% 103.61% at 78.44% 53.24%, #ADC1E1 0%, #476EAD 92.19%",

    description:
      "С проверенными продуктами готовить одно удовольствие. Они не подведут, они гарантируют результат. Именно поэтому они вдохновляют на новые кулинарные свершения. Молочные продукты под торговой маркой «ЭКОМИЛК» – те самые продукты, которые уже много лет занимают свое почетное место в холодильниках и ведут хозяек на новые кулинарные подвиги.",
    image: SourCream,
  },
  {
    id: 5,
    title: "Сыр",
    width: "320px",
    height: "240px",
    colorCard: "#9E672D",
    gradient: "177.19% 103.61% at 78.44% 53.24%, #E09D57 0%, #9E672D 92.19%",

    description:
      "С проверенными продуктами готовить одно удовольствие. Они не подведут, они гарантируют результат. Именно поэтому они вдохновляют на новые кулинарные свершения. Молочные продукты под торговой маркой «ЭКОМИЛК» – те самые продукты, которые уже много лет занимают свое почетное место в холодильниках и ведут хозяек на новые кулинарные подвиги.",
    image: ProcessedChocolateCheese,
  },
  {
    id: 6,
    title: "Кефир",
    width: "270px",
    height: "380.9px",
    colorCard: "#F59F9F",
    gradient: "177.19% 103.61% at 78.44% 53.24%, #FBB0B0 0%, #EB968F 100%",

    description:
      "С проверенными продуктами готовить одно удовольствие. Они не подведут, они гарантируют результат. Именно поэтому они вдохновляют на новые кулинарные свершения. Молочные продукты под торговой маркой «ЭКОМИЛК» – те самые продукты, которые уже много лет занимают свое почетное место в холодильниках и ведут хозяек на новые кулинарные подвиги.",
    image: Kefir,
  },
  {
    id: 7,
    title: "Творожный десерт",
    width: "260px",
    height: "260px",
    colorCard: "#4D6895",
    gradient: "229.14% 157.43% at -8.07% 202.24%, #08338F 0%, #8EA6D6 100%",
    description:
      "С проверенными продуктами готовить одно удовольствие. Они не подведут, они гарантируют результат. Именно поэтому они вдохновляют на новые кулинарные свершения. Молочные продукты под торговой маркой «ЭКОМИЛК» – те самые продукты, которые уже много лет занимают свое почетное место в холодильниках и ведут хозяек на новые кулинарные подвиги.",
    image: Curd,
  },
  {
    id: 8,
    title: "Сгущённое молоко",
    width: "180px",
    height: "370px",
    colorCard: "#37A1C5",
    gradient: "177.19% 103.61% at 78.44% 53.24%, #3EABD1 0%, #2288AB 100%",
    description:
      "С проверенными продуктами готовить одно удовольствие. Они не подведут, они гарантируют результат. Именно поэтому они вдохновляют на новые кулинарные свершения. Молочные продукты под торговой маркой «ЭКОМИЛК» – те самые продукты, которые уже много лет занимают свое почетное место в холодильниках и ведут хозяек на новые кулинарные подвиги.",
    image: CondensedMilk,
  },
]

export const catalogItem = [
  {
    id: 1,
    name: "Молоко",
    packageName: "Пюр-Пак",
    fatPercentage: "2,5% и 3,2%",
    day: "7 cуток",
    liter: "1 литр",
    additionalImg: [
      {
        id: 1,
        titlePercent: "Молоко 2,5",
        width: "250px",
        height: "410px",
        image: KefirWoilet,
        colorCard: "#B49FC3",
      },
      {
        id: 2,
        titlePercent: "Молоко 3,2",
        width: "250px",
        height: "410px",
        image: Milk,
        colorCard: "#B49FC3",
      },
    ],
  },

  {
    id: 2,
    name: "БИО Кефиры",
    packageName: "Пюр-Пак",
    fatPercentage: "2,5%",
    day: "7 cуток",
    liter: "1 литр",
    additionalImg: [
      {
        id: 1,
        titlePercent: "Биованиль 2,5%",
        width: "250px",
        height: "400.9px",
        image: Biokefir,
        colorCard: "#B5CB07",
      },
      {
        id: 2,
        titlePercent: "Био Клубника 2,5%",
        width: "410px",
        height: "490.9px",
        image: Strawberry,
        colorCard: "#F2A998",
      },
    ],
  },
  {
    id: 3,
    name: "Масло",
    packageName: "Пюр-Пак",
    fatPercentage: "2,5%",
    day: "7 cуток",
    liter: "1 литр",
    additionalImg: [
      {
        id: 1,
        titlePercent: "Масло",
        width: "260px",
        height: "350.9px",
        image: Butter,
        colorCard: "#D2AF4A",
      },
    ],
  },
  {
    id: 4,
    name: "Каймак",
    packageName: "Пюр-Пак",
    fatPercentage: "2,5%",
    day: "7 cуток",
    liter: "1 литр",
    additionalImg: [
      {
        id: 1,
        titlePercent: "Каймак",
        width: "270px",
        height: "220.9px",
        image: SourCream,
        colorCard: "#A5BADD",
      },
      {
        id: 2,
        titlePercent: "Каймак",
        width: "240px",
        height: "300px",
        image: Smetana,
        colorCard: "#8ABF68",
      },
    ],
  },
  {
    id: 5,
    name: "Сыр",
    packageName: "Пюр-Пак",
    fatPercentage: "2,5%",
    day: "7 cуток",
    liter: "1 литр",
    additionalImg: [
      {
        id: 1,
        titlePercent: "Сыр Ванильный",
        width: "310px",
        height: "240px",
        image: ProcessedCheese,
        colorCard: "#E8A180",
      },
      {
        id: 2,
        titlePercent: "Сыр Шоколадный",
        width: "290px",
        height: "220px",
        image: ProcessedChocolateCheese,
        colorCard: "#9E672D",
      },
    ],
  },
  {
    id: 6,
    name: "Кефир",
    packageName: "Пюр-Пак",
    fatPercentage: "2,5%",
    day: "7 cуток",
    liter: "1 литр",
    additionalImg: [
      {
        id: 1,
        titlePercent: "Кефир полезный",
        width: "260px",
        height: "390.9px",
        image: Kefir,
        colorCard: "#F59F9F",
      },
      {
        id: 2,
        titlePercent: "Кефир кисломолочный",
        width: "260px",
        height: "390.9px",
        image: BlueKefir,
        colorCard: "#1D80BB",
      },
    ],
  },
  {
    id: 7,
    name: "Творожный десерт",
    packageName: "Пюр-Пак",
    fatPercentage: "2,5%",
    day: "7 cуток",
    liter: "1 литр",
    additionalImg: [
      {
        id: 1,
        titlePercent: "Творожный десерт со вкусом Киви",
        width: "302px",
        height: "303px",
        image: CurdKiwi,
        colorCard: "#7DBA00",
      },
      {
        id: 2,
        titlePercent: "Творожный десерт со вкусом Клубники",
        width: "302px",
        height: "303px",
        image: CurdStrawberry,
        colorCard: "#D94F00",
      },
      {
        id: 3,
        titlePercent: "Творожный десертсо вкусом Шоколада",
        width: "302px",
        height: "303px",
        image: CurdChocolate,
        colorCard: "#52291C",
      },
      {
        id: 4,
        titlePercent: "Творожный десерт со вкусом Изюма",
        width: "302px",
        height: "303px",
        image: Curd,
        colorCard: "#08338F",
      },
    ],
  },
  {
    id: 8,
    name: "Сгущённое молоко",
    packageName: "Пюр-Пак",
    fatPercentage: "2,5%",
    day: "7 cуток",
    liter: "1 литр",
    additionalImg: [
      {
        id: 1,
        titlePercent: "Сгущенное молоко",
        width: "180px",
        height: "380px",
        image: CondensedMilk,
        colorCard: "#A5BADD",
      },
      {
        id: 2,
        titlePercent: "Сгущенное молоко",
        width: "400px",
        height: "290px",
        image: MiniCondensedMilk,
        colorCard: "#297FA8",
      },
    ],
  },
]

export const SLIDES = [
  {
    id: 1,
    image: SlideOne,
  },
  {
    id: 2,
    image: SlideTwo,
    motion_item: ItemTwo,
  },
  {
    id: 3,
    image: SlideThree,
    motion_item: ItemThree,
  },
  {
    id: 4,
    image: SlideFour,
    motion_item: ItemFour,
  },
  {
    id: 5,
    image: SlideFive,
    motion_item: ItemFive,
  },
]
